#!/usr/bin/env bash

USER_BIN_PATH="$HOME/bin"

if [ ! -d "$USER_BIN_PATH" ]; then
    mkdir -p "$USER_BIN_PATH"
fi

if [ -f "$USER_BIN_PATH/suurv" ]; then
    rm "$USER_BIN_PATH/suurv"
fi

cp suurv tmp
chmod u+x tmp
mv tmp "$USER_BIN_PATH/suurv"
